### ISSUE TITLE
Running it locally?

### ISSUE THREAD

**Issue by AstromonkeyIO** [jeffwillette/react-awesome-resume#2]
Hi there, I'm trying to run this locally and wanted to know which port the application will be hosted.

**Comment by jeffwillette** [comment]
It is built to be importable into your own react app which is run from wherever your react app runs from...

If you just clone the repo and run `yarn start` it will build everything into the `./build` dir and watch for rebuilds. ,but it doesn't serve them.

The easiest way to go would be to use `create-react-app` to make your own react app and then import this as a package

**Comment by AstromonkeyIO** [comment]
Yup, realized that right after I created that issue haha. Thanks for the
response anyways.

Best,

Tom



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality3&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality3&>
