### ISSUE TITLE
Issue when hovering over skills

### ISSUE THREAD

**Issue by alexvicegrab** [jeffwillette/react-awesome-resume#4]
When running `npm start` the CV builds correctly (after adjusting some bits and pieces in JSON resume).

However, when I hover on the skills all goes blank and I see the following error in the Chrome Development Tools:

```
_processChildContext is not available in React 16+. This likely means you have multiple copies of React and are attempting to nest a React 15 tree inside a React 16 tree using unstable_renderSubtreeIntoContainer, which isn't supported. Try to make sure you have only one copy of React (and ideally, switch to ReactDOM.createPortal)
```

**Comment by alexvicegrab** [comment]
Aha, this is because we need to upgrade to React 16. I managed to get it working (mostly) on React 15 with `create-react-app`, but was unable to upgrade my Fork to React 16 for now.

**Comment by jeffwillette** [comment]
were you importing it into another project?

**Comment by alexvicegrab** [comment]
Yes, I was not clear on how to start it with `person.js`, so I made a create-react-app and imported my fork with adjusted dependencies.

**Comment by hpierre74** [comment]
Wouldn't it be preferable to use react/react-dom as peer dependencies in this project ?

**Comment by jeffwillette** [comment]
ok, looks like everything is working now then
